/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef } from 'react';
import { Download, Upload, CheckCircle2, AlertCircle, Database, ShieldAlert, Info } from 'lucide-react';
import { Member, Contribution, ChurchPreferences } from '../types';

interface AdminPortalProps {
  members: Member[];
  contributions: Contribution[];
  preferences: ChurchPreferences;
  onImportData: (data: { members: Member[]; contributions: Contribution[]; preferences: ChurchPreferences }) => void;
  isAdmin: boolean;
}

export default function AdminPortal({ 
  members, 
  contributions, 
  preferences, 
  onImportData, 
  isAdmin 
}: AdminPortalProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [statusMsg, setStatusMsg] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleExportLocal = () => {
    try {
      setIsLoading(true);
      const dataToExport = {
        version: '1.1.2',
        timestamp: new Date().toISOString(),
        members,
        contributions,
        preferences
      };
      
      const blob = new Blob([JSON.stringify(dataToExport, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      
      const downloadAnchor = document.createElement('a');
      const timestamp = new Date().toISOString().slice(0, 10);
      downloadAnchor.href = url;
      downloadAnchor.download = `sda_church_ledger_backup_${timestamp}.json`;
      
      document.body.appendChild(downloadAnchor);
      downloadAnchor.click();
      document.body.removeChild(downloadAnchor);
      
      URL.revokeObjectURL(url);
      
      setStatusMsg({
        type: 'success',
        text: 'Backup file successfully generated and downloaded to your local device!'
      });
    } catch (err) {
      console.error(err);
      setStatusMsg({
        type: 'error',
        text: 'Failed to generate backup: ' + (err as Error).message
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleImportLocal = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    if (!confirm('This will OVERWRITE all your current active local data (members list, contributions ledger, and configuration preferences). Are you sure you want to proceed?')) {
      event.target.value = '';
      return;
    }

    setIsLoading(true);
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const parsed = JSON.parse(content);
        
        // Structure validation assertion
        if (parsed && Array.isArray(parsed.members) && Array.isArray(parsed.contributions)) {
          onImportData({
            members: parsed.members,
            contributions: parsed.contributions,
            preferences: parsed.preferences || preferences
          });
          
          setStatusMsg({
            type: 'success',
            text: `Successfully restored workspace state! Loaded ${parsed.members.length} members and ${parsed.contributions.length} ledger logs.`
          });
        } else {
          throw new Error('Invalid backup schema. The backup file must be a valid JSON generated by this church steward software containing both members and contributions lists.');
        }
      } catch (err) {
        console.error(err);
        setStatusMsg({
          type: 'error',
          text: 'Failed to parse backup format: ' + (err as Error).message
        });
      } finally {
        setIsLoading(false);
      }
    };

    reader.onerror = () => {
      setStatusMsg({
        type: 'error',
        text: 'Failed to access the backup file.'
      });
      setIsLoading(false);
    };

    reader.readAsText(file);
    // Clear selection so selecting the same file again triggers change event
    event.target.value = '';
  };

  const triggerFileInput = () => {
    if (!isAdmin) {
      setStatusMsg({
        type: 'error',
        text: '🔑 Writing signature required. Please activate Admin Mode using the switch in the top toolbar to import backup databases.'
      });
      return;
    }
    fileInputRef.current?.click();
  };

  return (
    <div className="space-y-6 animate-fade-in" id="local-data-portal">
      {/* Dynamic Notifications */}
      {statusMsg && (
        <div className={`p-4 rounded-xl flex items-start gap-3 animate-fade-in ${
          statusMsg.type === 'success' 
            ? 'bg-emerald-50 text-emerald-800 border border-emerald-100' 
            : 'bg-rose-50 text-rose-800 border border-rose-100'
        }`}>
          {statusMsg.type === 'success' ? <CheckCircle2 size={16} className="mt-0.5 text-emerald-600 shrink-0" /> : <AlertCircle size={16} className="mt-0.5 text-rose-600 shrink-0" />}
          <div className="flex-1">
            <p className="text-[10px] font-black uppercase tracking-wider">{statusMsg.type === 'success' ? 'Success Notification' : 'Attention / Error'}</p>
            <p className="text-xs leading-normal font-medium mt-0.5">{statusMsg.text}</p>
          </div>
          <button 
            onClick={() => setStatusMsg(null)} 
            className="text-[10px] font-bold text-slate-400 hover:text-slate-650 px-2 py-0.5 hover:bg-slate-100 rounded transition"
          >
            Clear
          </button>
        </div>
      )}

      {/* Grid Canvas for Local Backup UI */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Core Description Header Column */}
        <div className="lg:col-span-1 space-y-4">
          <div className="bg-white border border-slate-100 p-6 rounded-2xl shadow-xs space-y-3">
            <h2 className="text-sm font-bold text-slate-800 flex items-center gap-1.5 uppercase tracking-wide">
              <Database className="text-slate-400 font-bold" size={16} />
              Local Database Backup Center
            </h2>
            <p className="text-xs text-slate-505 leading-relaxed">
              Safeguard your data without compromising privacy. Save a snapshot file to your computer, phone, or memory card, and instantly restore everything back in case of device reset.
            </p>
            <div className="bg-slate-50 border border-slate-150 p-3 rounded-lg flex items-start gap-2">
              <Info className="text-blue-500 mt-0.5 shrink-0" size={14} />
              <p className="text-[10px] text-slate-500 leading-normal">
                All records are processed completely in-browser. Your church financial registers never leave your local machine.
              </p>
            </div>
          </div>
        </div>

        {/* Action Panel Column */}
        <div className="lg:col-span-2 grid grid-cols-1 md:grid-cols-2 gap-4">
          
          {/* Card: Export Database Archive */}
          <div className="bg-white border border-slate-100 p-6 rounded-2xl shadow-xs flex flex-col justify-between hover:border-blue-200 transition-all group duration-300">
            <div className="space-y-2">
              <div className="w-10 h-10 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center border border-blue-100 group-hover:scale-105 transition-transform">
                <Download size={20} />
              </div>
              <h3 className="text-xs font-black text-slate-800 uppercase tracking-widest pt-2">Download Local Backup</h3>
              <p className="text-[11px] text-slate-500 leading-normal">
                Generate and download an encrypted workspace data payload containing your members listings, full bookkeeping registers, and allocations settings.
              </p>
            </div>

            <div className="pt-6">
              <button
                disabled={isLoading}
                onClick={handleExportLocal}
                className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-sm shadow-blue-100 hover:shadow-md transition cursor-pointer flex items-center justify-center gap-2"
              >
                <Download size={13} />
                <span>Download Snapshot (.json)</span>
              </button>
            </div>
          </div>

          {/* Card: Import Database Archive */}
          <div className="bg-white border border-slate-100 p-6 rounded-2xl shadow-xs flex flex-col justify-between hover:border-emerald-200 transition-all group duration-300 relative overflow-hidden">
            <div className="space-y-2">
              <div className="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center border border-emerald-100 group-hover:scale-105 transition-transform">
                <Upload size={20} />
              </div>
              <h3 className="text-xs font-black text-slate-800 uppercase tracking-widest pt-2">Upload & Restore Archive</h3>
              <p className="text-[11px] text-slate-500 leading-normal">
                Choose a previously exported snapshot file from your device directory to import. This will merge or overwrite current data fields with the file states.
              </p>
            </div>

            <div className="pt-6">
              {/* Hidden Native Input */}
              <input 
                type="file"
                ref={fileInputRef}
                onChange={handleImportLocal}
                accept=".json"
                className="hidden"
              />

              {!isAdmin ? (
                <div className="bg-amber-50/70 border border-amber-150 rounded-xl p-3 text-[10px] text-slate-600 flex items-start gap-1.5 leading-normal">
                  <ShieldAlert className="text-amber-500 mt-0.5 shrink-0" size={13} />
                  <p>
                    <strong className="text-slate-800 font-bold">Import Restricted:</strong> Switch to <span className="font-bold underline text-rose-600">Admin Mode</span> using the switch in the top bar to restore backup databases.
                  </p>
                </div>
              ) : (
                <button
                  disabled={isLoading}
                  onClick={triggerFileInput}
                  className="w-full py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shadow-sm shadow-emerald-100 hover:shadow-md transition cursor-pointer flex items-center justify-center gap-2"
                >
                  <Upload size={13} />
                  <span>Restore Snapshot File</span>
                </button>
              )}
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
