/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef } from 'react';
import { Download, Upload, CheckCircle2, AlertCircle, Database, ShieldAlert, Info, Lock, X, Eye } from 'lucide-react';
import { Member, Contribution, ChurchPreferences } from '../types';

interface AdminPortalProps {
  members: Member[];
  contributions: Contribution[];
  preferences: ChurchPreferences;
  onImportData: (data: { members: Member[]; contributions: Contribution[]; preferences: ChurchPreferences }) => void;
  isAdmin: boolean;
}

export default function AdminPortal({ 
  members, 
  contributions, 
  preferences, 
  onImportData, 
  isAdmin 
}: AdminPortalProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [statusMsg, setStatusMsg] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Secure Password Challenge States
  const [verificationModal, setVerificationModal] = useState<'download' | 'restore' | null>(null);
  const [passwordField, setPasswordField] = useState('');
  const [passwordError, setPasswordError] = useState('');
  const [parsedImportData, setParsedImportData] = useState<any | null>(null);
  const [showPassword, setShowPassword] = useState(false);

  const handleExportLocal = () => {
    setVerificationModal('download');
    setPasswordField('');
    setPasswordError('');
    setShowPassword(false);
  };

  const executeExportLocal = () => {
    try {
      setIsLoading(true);
      const dataToExport = {
        version: '1.1.2',
        timestamp: new Date().toISOString(),
        members,
        contributions,
        preferences
      };
      
      const blob = new Blob([JSON.stringify(dataToExport, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      
      const downloadAnchor = document.createElement('a');
      const timestamp = new Date().toISOString().slice(0, 10);
      downloadAnchor.href = url;
      downloadAnchor.download = `sda_church_ledger_backup_${timestamp}.json`;
      
      document.body.appendChild(downloadAnchor);
      downloadAnchor.click();
      document.body.removeChild(downloadAnchor);
      
      URL.revokeObjectURL(url);
      
      setStatusMsg({
        type: 'success',
        text: 'Backup file successfully generated and downloaded to your local device!'
      });
    } catch (err) {
      console.error(err);
      setStatusMsg({
        type: 'error',
        text: 'Failed to generate backup: ' + (err as Error).message
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleImportLocal = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setIsLoading(true);
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const parsed = JSON.parse(content);
        
        // Structure validation assertion
        if (parsed && Array.isArray(parsed.members) && Array.isArray(parsed.contributions)) {
          setParsedImportData(parsed);
          setVerificationModal('restore');
          setPasswordField('');
          setPasswordError('');
          setShowPassword(false);
        } else {
          throw new Error('Invalid backup data. The backup file must be a valid JSON generated by this church steward software containing both members and contributions lists.');
        }
      } catch (err) {
        console.error(err);
        setStatusMsg({
          type: 'error',
          text: 'Failed to parse backup format: ' + (err as Error).message
        });
      } finally {
        setIsLoading(false);
      }
    };

    reader.onerror = () => {
      setStatusMsg({
        type: 'error',
        text: 'Failed to access the backup file.'
      });
      setIsLoading(false);
    };

    reader.readAsText(file);
    // Clear selection so selecting the same file again triggers change event
    event.target.value = '';
  };

  const executeImportDataApply = () => {
    if (!parsedImportData) return;
    try {
      onImportData({
        members: parsedImportData.members,
        contributions: parsedImportData.contributions,
        preferences: parsedImportData.preferences || preferences
      });
      
      setStatusMsg({
        type: 'success',
        text: `Successfully restored workspace state! Loaded ${parsedImportData.members.length} members and ${parsedImportData.contributions.length} ledger logs.`
      });
    } catch (err) {
      console.error(err);
      setStatusMsg({
        type: 'error',
        text: 'Failed to restore snapshot: ' + (err as Error).message
      });
    } finally {
      setParsedImportData(null);
    }
  };

  const triggerFileInput = () => {
    if (!isAdmin) {
      setStatusMsg({
        type: 'error',
        text: '🔑 Writing signature required. Please activate Admin Mode using the switch in the top toolbar to import backup databases.'
      });
      return;
    }
    fileInputRef.current?.click();
  };

  return (
    <div className="space-y-6 animate-fade-in" id="local-data-portal">
      {/* Dynamic Notifications */}
      {statusMsg && (
        <div className={`p-4 rounded-xl flex items-start gap-3 animate-fade-in ${
          statusMsg.type === 'success' 
            ? 'bg-emerald-50 text-emerald-800 border border-emerald-100' 
            : 'bg-rose-50 text-rose-800 border border-rose-100'
        }`}>
          {statusMsg.type === 'success' ? <CheckCircle2 size={16} className="mt-0.5 text-emerald-600 shrink-0" /> : <AlertCircle size={16} className="mt-0.5 text-rose-600 shrink-0" />}
          <div className="flex-1">
            <p className="text-[10px] font-black uppercase tracking-wider">{statusMsg.type === 'success' ? 'Success Notification' : 'Attention / Error'}</p>
            <p className="text-xs leading-normal font-medium mt-0.5">{statusMsg.text}</p>
          </div>
          <button 
            onClick={() => setStatusMsg(null)} 
            className="text-[10px] font-bold text-slate-400 hover:text-slate-650 px-2 py-0.5 hover:bg-slate-100 rounded transition"
          >
            Clear
          </button>
        </div>
      )}

      {/* Grid Canvas for Local Backup UI */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Core Description Header Column */}
        <div className="lg:col-span-1 space-y-4">
          <div className="bg-white border border-slate-100 p-6 rounded-2xl shadow-xs space-y-3">
            <h2 className="text-sm font-bold text-slate-800 flex items-center gap-1.5 uppercase tracking-wide">
              <Database className="text-slate-400 font-bold" size={16} />
              Local Database Backup Center
            </h2>
            <p className="text-xs text-slate-505 leading-relaxed">
              Safeguard your data without compromising privacy. Save a snapshot file to your computer, phone, or memory card, and instantly restore everything back in case of device reset.
            </p>
            <div className="bg-slate-50 border border-slate-150 p-3 rounded-lg flex items-start gap-2">
              <Info className="text-blue-500 mt-0.5 shrink-0" size={14} />
              <p className="text-[10px] text-slate-500 leading-normal">
                All records are processed completely in-browser. Your church financial registers never leave your local machine.
              </p>
            </div>
          </div>
        </div>

        {/* Action Panel Column */}
        <div className="lg:col-span-2 grid grid-cols-1 md:grid-cols-2 gap-4">
          
          {/* Card: Export Database Archive */}
          <div className="bg-white border border-slate-100 p-6 rounded-2xl shadow-xs flex flex-col justify-between hover:border-blue-200 transition-all group duration-300">
            <div className="space-y-2">
              <div className="w-10 h-10 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center border border-blue-100 group-hover:scale-105 transition-transform">
                <Download size={20} />
              </div>
              <h3 className="text-xs font-black text-slate-800 uppercase tracking-widest pt-2">Download Local Backup</h3>
              <p className="text-[11px] text-slate-500 leading-normal">
                Generate and download an encrypted workspace data payload containing your members listings, full bookkeeping registers, and allocations settings.
              </p>
            </div>

            <div className="pt-6">
              <button
                disabled={isLoading}
                onClick={handleExportLocal}
                className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-sm shadow-blue-100 hover:shadow-md transition cursor-pointer flex items-center justify-center gap-2"
              >
                <Download size={13} />
                <span>Download Snapshot (.json)</span>
              </button>
            </div>
          </div>

          {/* Card: Import Database Archive */}
          <div className="bg-white border border-slate-100 p-6 rounded-2xl shadow-xs flex flex-col justify-between hover:border-emerald-200 transition-all group duration-300 relative overflow-hidden">
            <div className="space-y-2">
              <div className="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center border border-emerald-100 group-hover:scale-105 transition-transform">
                <Upload size={20} />
              </div>
              <h3 className="text-xs font-black text-slate-800 uppercase tracking-widest pt-2">Upload & Restore Archive</h3>
              <p className="text-[11px] text-slate-500 leading-normal">
                Choose a previously exported snapshot file from your device directory to import. This will merge or overwrite current data fields with the file states.
              </p>
            </div>

            <div className="pt-6">
              {/* Hidden Native Input */}
              <input 
                type="file"
                ref={fileInputRef}
                onChange={handleImportLocal}
                accept=".json"
                className="hidden"
              />

              {!isAdmin ? (
                <div className="bg-amber-50/70 border border-amber-150 rounded-xl p-3 text-[10px] text-slate-600 flex items-start gap-1.5 leading-normal">
                  <ShieldAlert className="text-amber-500 mt-0.5 shrink-0" size={13} />
                  <p>
                    <strong className="text-slate-800 font-bold">Import Restricted:</strong> Switch to <span className="font-bold underline text-rose-600">Admin Mode</span> using the switch in the top bar to restore backup databases.
                  </p>
                </div>
              ) : (
                <button
                  disabled={isLoading}
                  onClick={triggerFileInput}
                  className="w-full py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shadow-sm shadow-emerald-100 hover:shadow-md transition cursor-pointer flex items-center justify-center gap-2"
                >
                  <Upload size={13} />
                  <span>Restore Snapshot File</span>
                </button>
              )}
            </div>
          </div>

        </div>

      </div>

      {/* SECURITY CHALLENGE VERIFICATION MODAL */}
      {verificationModal && (
        <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 animate-fade-in" id="security-verification-modal">
          <div className="bg-white rounded-2xl max-w-sm w-full shadow-xl border border-slate-100 overflow-hidden" onClick={(e) => e.stopPropagation()}>
            {/* Header banner */}
            <div className={`px-5 py-4 text-white flex items-center justify-between ${
              verificationModal === 'restore' 
                ? 'bg-gradient-to-r from-emerald-600 to-emerald-700' 
                : 'bg-gradient-to-r from-blue-600 to-blue-700'
            }`}>
              <div className="flex items-center gap-3">
                <div className="bg-white/20 p-2 rounded-lg">
                  <Lock size={18} className="text-white" />
                </div>
                <div>
                  <h3 className="text-xs font-black tracking-tight uppercase">Admin Verification</h3>
                  <p className="text-[10px] text-white/90 font-medium font-sans">
                    {verificationModal === 'restore' ? 'Overwrite Confirmation Required' : 'Authorization Required'}
                  </p>
                </div>
              </div>
              <button 
                type="button" 
                onClick={() => {
                  setVerificationModal(null);
                  setParsedImportData(null);
                  setPasswordField('');
                  setPasswordError('');
                }}
                className="p-1 hover:bg-white/10 rounded-lg transition text-white"
              >
                <X size={16} />
              </button>
            </div>

            {/* Form */}
            <form onSubmit={(e) => {
              e.preventDefault();
              if (passwordField === 'password123') {
                if (verificationModal === 'download') {
                  executeExportLocal();
                } else if (verificationModal === 'restore' && parsedImportData) {
                  executeImportDataApply();
                }
                setVerificationModal(null);
                setPasswordField('');
                setPasswordError('');
              } else {
                setPasswordError('Invalid Administrator password.');
              }
            }} className="p-5 space-y-4">
              
              <p className="text-[11px] text-slate-500 leading-normal">
                {verificationModal === 'restore' ? (
                  <>
                    ⚠️ <strong>WARNING:</strong> This action will overwrite all current members data, tithes registers, and configurations in local storage. Please enter the Administrator password to apply.
                  </>
                ) : (
                  'Please enter your administrative password to authorize and generate your local database backup file.'
                )}
              </p>

              {verificationModal === 'restore' && parsedImportData && (
                <div className="bg-indigo-50 border border-indigo-150 p-3 rounded-xl space-y-1 text-[10px]">
                  <p className="font-bold text-indigo-900 uppercase tracking-wide">Backup Content Stats:</p>
                  <ul className="list-disc list-inside text-indigo-850 space-y-0.5">
                    <li>Members to register: <strong className="font-bold">{parsedImportData.members?.length || 0}</strong></li>
                    <li>Receipt registers: <strong className="font-bold">{parsedImportData.contributions?.length || 0}</strong></li>
                    <li>Timestamp: <strong className="font-mono">{parsedImportData.timestamp ? new Date(parsedImportData.timestamp).toLocaleString() : 'N/A'}</strong></li>
                  </ul>
                </div>
              )}

              {passwordError && (
                <div className="bg-rose-50 border border-rose-200 text-rose-700 px-3 py-1.5 rounded-lg text-[11px] font-bold flex items-center gap-1.5">
                  <ShieldAlert size={13} className="shrink-0 text-rose-600" />
                  <span>{passwordError}</span>
                </div>
              )}

              <div className="space-y-1.5">
                <label className="block text-[9px] uppercase font-bold text-slate-500 tracking-wider">Admin Password</label>
                <div className="relative">
                  <input
                    type={showPassword ? "text" : "password"}
                    required
                    placeholder="••••••••"
                    value={passwordField}
                    onChange={(e) => setPasswordField(e.target.value)}
                    className="w-full pl-3 pr-10 py-1.5 border border-slate-200 rounded-lg text-xs font-semibold text-slate-700 outline-none focus:ring-1 focus:ring-slate-400 transition-all font-mono"
                    autoFocus
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-2 top-1/2 -translate-y-1/2 p-1 text-slate-400 hover:text-slate-650 transition"
                  >
                    <Eye size={14} />
                  </button>
                </div>
              </div>

              {/* Actions */}
              <div className="pt-2 flex gap-2">
                <button
                  type="button"
                  onClick={() => {
                    setVerificationModal(null);
                    setParsedImportData(null);
                    setPasswordField('');
                    setPasswordError('');
                  }}
                  className="flex-1 py-1.5 border border-slate-200 rounded-lg text-xs font-bold text-slate-600 hover:bg-slate-50 transition cursor-pointer text-center font-sans"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className={`flex-1 py-1.5 text-white rounded-lg text-xs font-bold shadow-3xs transition cursor-pointer text-center font-sans ${
                    verificationModal === 'restore'
                      ? 'bg-emerald-600 hover:bg-emerald-700 hover:shadow-emerald-100'
                      : 'bg-blue-600 hover:bg-blue-700 hover:shadow-blue-100'
                  }`}
                >
                  Verify & Proceed
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

